<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8970" started-at="2019-06-06T05:35:10Z" finished-at="2019-06-06T05:35:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8970" started-at="2019-06-06T05:35:10Z" finished-at="2019-06-06T05:35:19Z">
      <class name="test.StackOverFlowTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:test.StackOverFlowTest@5faeada1]" name="setup" is-config="true" duration-ms="7542" started-at="2019-06-06T05:35:10Z" finished-at="2019-06-06T05:35:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyStackoverflowContaints()[pri:0, instance:test.StackOverFlowTest@5faeada1]" name="verifyStackoverflowContaints" duration-ms="152" started-at="2019-06-06T05:35:18Z" finished-at="2019-06-06T05:35:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Learn, Share, Build1] but found [Learn, Share, Build]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Learn, Share, Build1] but found [Learn, Share, Build]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at test.StackOverFlowTest.verifyStackoverflowContaints(StackOverFlowTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStackoverflowContaints -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:test.StackOverFlowTest@5faeada1]" name="tearDown" is-config="true" duration-ms="1023" started-at="2019-06-06T05:35:18Z" finished-at="2019-06-06T05:35:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyStackoverflowContaints status=FAILURE method=StackOverFlowTest.verifyStackoverflowContaints()[pri:0, instance:test.StackOverFlowTest@5faeada1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="verifyStackoverflowContaints2()[pri:0, instance:test.StackOverFlowTest@5faeada1]" name="verifyStackoverflowContaints2" duration-ms="103" started-at="2019-06-06T05:35:19Z" finished-at="2019-06-06T05:35:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStackoverflowContaints2 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:test.StackOverFlowTest@5faeada1]" name="tearDown" is-config="true" duration-ms="114" started-at="2019-06-06T05:35:19Z" finished-at="2019-06-06T05:35:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyStackoverflowContaints2 status=SUCCESS method=StackOverFlowTest.verifyStackoverflowContaints2()[pri:0, instance:test.StackOverFlowTest@5faeada1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.StackOverFlowTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
